services:
  - type: web
    name: product-service
    runtime: docker
    repo: https://github.com/boschtech/product-service
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: ORDER_SERVICE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
